name: Mango
title: Mango
baseurl: "/Mango"

excerpt_separator: <!--more-->
defaults:
 -
  scope:
    type: pages
  values:
    permalink: /:path/:basename:output_ext
 -
  scope:
    type: posts
  values:
    permalink: /:year/:month/:day/:title.html